# Generated by Django 5.2.6 on 2025-09-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='templates.template'),
        ),
    ]
